import Head from 'next/head'
import * as  echarts from 'echarts';
import { useEffect, useRef, useState } from 'react';
import styles from '../styles/Home.module.css'

export default function Home() {
  const [hp,setHP] = useState(0)
  const refContainer = useRef(null)
  useEffect(()=>{
    const myChart = echarts.init(refContainer.current)
    console.log(myChart)
    myChart.setOption({
      title: {
        text: 'ECharts Getting Started Example'
      },
      tooltip: {},
      xAxis: {
        data: ['shirt', 'cardigan', 'chiffon', 'pants', 'heels', 'socks']
      },
      yAxis: {},
      series: [
        {
          name: 'sales',
          type: 'bar',
          data: [5, 20, 36, 10, 10, 20]
        }
      ]
    });

  },[])
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {console.log(hp)}
      <main className={styles.main}>
        <div ref={refContainer} style={{
          height: "500px",
          width: "500px",
          background: "gray"
        }}>hey</div>
       <div>hello</div>
       <button onClick={()=>{setHP((x)=>(x+ 1))}}>hello</button>
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}
